# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            军行天下
tagline:          ''
description:      '进击的前端'
url:              http://junxtx.github.io/

author:
  name:           '军行天下'
  email:          junxtx@mail.com

paginate:      6

# Custom vars
version:          0.0.3

# Comments

comments :
    provider : duoshuo
    duoshuo :
          short_name : cellier-me


